local _, TRB = ...

-- Paladin options (World of Warcraft: Forever): default settings, default bar text and the options
-- panel for each specialization, generated by the options template from the class archetypes.
TRB.Forever.Templates.Options:Install("paladin")
