local _, TRB = ...

-- Rogue options (World of Warcraft: Forever): default settings, default bar text and the options
-- panel, generated by the options template from the class archetypes.

---Which threshold lines start enabled: the rotational abilities, with situational utility left off.
---@return table
local function LoadDefaultThresholdDictionary()
	return {
		sinisterStrike = { enabled = true },
		backstab = { enabled = true },
		mutilate = { enabled = true },
		hemorrhage = { enabled = true },
		ghostlyStrike = { enabled = true },
		ambush = { enabled = true },
		garrote = { enabled = true },
		cheapShot = { enabled = true },
		gouge = { enabled = true },
		riposte = { enabled = false },
		eviscerate = { enabled = true },
		rupture = { enabled = true },
		sliceAndDice = { enabled = true },
		kidneyShot = { enabled = true },
		exposeArmor = { enabled = true },
		venom = { enabled = true },
		feint = { enabled = false },
		sap = { enabled = false },
		kick = { enabled = true },
		distract = { enabled = false },
		blind = { enabled = false },
		bladeFlurry = { enabled = true },
	}
end

TRB.Forever.Templates.Options:Install("rogue", {
	general = LoadDefaultThresholdDictionary,
})
