local _, TRB = ...

-- Warrior options (World of Warcraft: Forever): default settings, default bar text and the options
-- panel, generated by the options template from the class archetypes.

---Which threshold lines start enabled: the rotational abilities, with situational utility left off.
---@return table
local function LoadDefaultThresholdDictionary()
	return {
		heroicStrike = { enabled = true },
		cleave = { enabled = true },
		rend = { enabled = true },
		thunderClap = { enabled = true },
		overpower = { enabled = true },
		execute = { enabled = true },
		sunderArmor = { enabled = true },
		revenge = { enabled = true },
		slam = { enabled = true },
		whirlwind = { enabled = true },
		shieldSlam = { enabled = true },
		mortalStrike = { enabled = true },
		bloodthirst = { enabled = true },
		deathWish = { enabled = true },
		sweepingStrikes = { enabled = true },
		spearingStrike = { enabled = true },
		hamstring = { enabled = true },
		shieldBash = { enabled = true },
		intercept = { enabled = true },
		pummel = { enabled = true },
		battleShout = { enabled = true },
		demoralizingShout = { enabled = true },
		intimidatingShout = { enabled = false },
		disarm = { enabled = false },
		concussionBlow = { enabled = true },
		piercingHowl = { enabled = false },
		shieldBlock = { enabled = true },
		challengingShout = { enabled = false },
		mockingBlow = { enabled = false },
	}
end

TRB.Forever.Templates.Options:Install("warrior", {
	general = LoadDefaultThresholdDictionary,
})
